# .travis.yml
#
# This is the configuration file to drive Travis CI for Slang.

language: cpp

# Build and test (clang, gcc) x (debug, release)

env:
  OMP_NUM_THREADS=1

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - CONFIGURATION=debug
    - os: linux
      compiler: clang
      env:
        - CONFIGURATION=debug
    - os: linux
      compiler: clang
      env:
        - CONFIGURATION=release
    - os: linux
      compiler: gcc
      env:
        - CONFIGURATION=release

script: bash ./get_examplegame.sh && make test