# Our solution file is currently set up for VS2015
image: Visual Studio 2019

init:
# The project uses a submodule for the "glslang" dependency,
# so we need to make sure to pull that before building.
install:
  - ps: |
  git submodule update --init --recursive
  ./get_examplegame.ps1
  ./prepare.ps1

# We want to build the full matrix of platforms and configurations
# that we support on Windows.
#
# Put Release|x64 first since that is the target which runs the most tests.
platform:
  - x64

configuration:
  - Release
  - Debug

# In the interests of time, go ahead and immediately fail a build
# if any job fails, rather than keep on building to discover the
# full set of failures.
matrix:
  fast_finish: true

# MSBUILD should ideally be able to find our solution file
# automatically, but it seems to get confused, so we specify
# the file name to use here.
build:
  project: GameEngine.sln
  parallel: true
  verbosity: minimal

# Testing

test_script:
  - ps: |
      .\run_test.ps1